from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="rml-ai",
    version="1.0.0",
    author="RML-AI Team",
    author_email="team@rml-ai.com",
    description="🚀 Resonant Memory Learning - A Revolutionary AI Paradigm Beyond Traditional LLMs",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/akshaynayaks9845/rml-ai",
    project_urls={
        "Bug Reports": "https://github.com/akshaynayaks9845/rml-ai/issues",
        "Source": "https://github.com/akshaynayaks9845/rml-ai",
        "Documentation": "https://github.com/akshaynayaks9845/rml-ai/docs",
        "Hugging Face Datasets": "https://huggingface.co/datasets/akshaynayaks9845/rml-ai-datasets",
        "Trained Model": "https://huggingface.co/akshaynayaks9845/rml-ai-phi1_5-rml-100k",
    },
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Science/Research",
        "Intended Audience :: Developers",
        "Intended Audience :: Information Technology",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Text Processing :: Linguistic",
        "Topic :: Scientific/Engineering :: Information Analysis",
    ],
    python_requires=">=3.8",
    install_requires=[
        "torch>=2.0.0",
        "transformers>=4.30.0",
        "sentence-transformers>=2.2.0",
        "numpy>=1.21.0",
        "scikit-learn>=1.0.0",
        "fastapi>=0.100.0",
        "uvicorn[standard]>=0.20.0",
        "pydantic>=2.0.0",
        "requests>=2.28.0",
        "tqdm>=4.64.0",
        "huggingface-hub>=0.16.0",
        "accelerate>=0.20.0",
        "datasets>=2.12.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "pytest-cov>=4.0.0",
            "black>=23.0.0",
            "isort>=5.12.0",
            "flake8>=6.0.0",
            "mypy>=1.0.0",
        ],
        "training": [
            "wandb>=0.15.0",
            "tensorboard>=2.12.0",
            "deepspeed>=0.9.0",
        ],
        "deployment": [
            "docker>=6.0.0",
            "kubernetes>=26.0.0",
        ],
    },
    entry_points={
        "console_scripts": [
            "rml-ai=rml_ai.cli:main",
            "rml-server=rml_ai.server:main",
        ],
    },
    keywords=[
        "artificial-intelligence",
        "machine-learning",
        "resonant-memory-learning",
        "rml",
        "transformer",
        "language-model",
        "semantic-search",
        "vector-database",
        "continuous-learning",
        "explainable-ai",
        "hallucination-control",
        "frequency-resonance",
        "neural-symbolic",
        "real-time-learning",
        "zero-forgetting",
        "sub-50ms-latency",
        "100x-memory-efficient",
        "90-percent-energy-savings",
    ],
    include_package_data=True,
    zip_safe=False,
)
